name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: true
        default: 'patch'
      distTag:
        description: 'NPM tag (e.g. use "next" to release a test version)'
        required: true
        default: 'latest'

permissions:
  contents: write

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: NPM Setup
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Git Setup
        run: |
          git config --global user.email "inluxc@gmail.com"
          git config --global user.name "Fúlvio Carvalhido"
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
        env:
          NODE_ENV: production
      - name: Release
        run: npm run release:ci -- ${{github.event.inputs.releaseType}} --npm.tag=${{github.event.inputs.distTag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
